import React from 'react';
import {
  Award,
  ShieldCheck,
  HardHat,
  HeartPulse,
  Flame,
  FileCheck,
  Construction,
  AlertTriangle,
  Box,
  ClipboardCheck,
  CheckCheck,
  Leaf,
  Lock,
  PhoneCall,
  ArrowUpCircle,
  Layers,
  Zap,
  Building2,
  Eye,
  ClipboardList,
  GraduationCap,
  QrCode,
  CheckCircle2,
  XCircle,
  Clock,
  Search,
  Printer,
  Download,
  Share2,
  ExternalLink,
  Shield,
  HelpCircle,
  FileText,
  UserCheck,
  BookOpen,
  Calendar,
  User,
  Hash,
  School,
  Sparkles,
  RefreshCw,
  Database,
  KeyRound,
  Trash2,
  Edit,
  PlusCircle,
  Info
} from 'lucide-react';

interface DynamicIconProps {
  name: string;
  className?: string;
  size?: number;
}

export const DynamicIcon: React.FC<DynamicIconProps> = ({ name, className = 'w-5 h-5', size }) => {
  const iconMap: Record<string, React.ComponentType<{ className?: string; size?: number }>> = {
    Award,
    ShieldCheck,
    HardHat,
    HeartPulse,
    Flame,
    FileCheck,
    Construction,
    AlertTriangle,
    Box,
    ClipboardCheck,
    CheckCheck,
    Leaf,
    Lock,
    PhoneCall,
    ArrowUpCircle,
    Layers,
    Zap,
    Building2,
    Eye,
    ClipboardList,
    GraduationCap,
    QrCode,
    CheckCircle2,
    XCircle,
    Clock,
    Search,
    Printer,
    Download,
    Share2,
    ExternalLink,
    Shield,
    HelpCircle,
    FileText,
    UserCheck,
    BookOpen,
    Calendar,
    User,
    Hash,
    School,
    Sparkles,
    RefreshCw,
    Database,
    KeyRound,
    Trash2,
    Edit,
    PlusCircle,
    Info
  };

  const IconComponent = iconMap[name] || ShieldCheck;
  return <IconComponent className={className} size={size} />;
};
